# Generated by Django 4.1.5 on 2023-10-19 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bname', models.CharField(max_length=20)),
                ('bauthor', models.CharField(max_length=20)),
                ('bpublishdate', models.DateField()),
            ],
        ),
    ]
